name: ai

channels:
- conda-forge
- defaults

dependencies:
- pandas=0.22
- pillow=4.3.0
- python=3.6
- scipy=0.19.1
- numpy
- matplotlib
- jupyter
- opencv
- pillow
- scikit-learn
- scikit-image
- h5py
- eventlet
- flask-socketio
- seaborn
- imageio
- wget
- pip:
  - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
  - moviepy
  - keras==2.0.8
  - python-socketio
  - gym
  - gym[atari]
